name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.Home_Server }}
    - name: Deploy to server
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        ssh-keyscan yourserver >> $HOME/.ssh/known_hosts
        ssh qleqs@bumblebee.giize.com "cd /containers/Raqin-website/Portfolio && git pull"

