name: Deployment workflow

on:
  push:
    branches:
      - master

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: test server ssh
        uses: appleboy/ssh-action@master
        with:
          host: bumblebee.giize.com
          username: qleqs
          key: ${{secrets.HOME_SECRET}}
          port: 22
          script:
            cd Containers/Raqin-website/Portfolio
            git pull origin master
            docker stop my-react-app
            docker rm my-react-app
            docker run --name my-react-app -d -p 80:80 -v $(pwd):/usr/src/app my-react-app


