
name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH key
      uses: actions/setup-ssh@v1
      with:
        ssh-key: ${{ secrets.Home_Server }}
    - name: Deploy to server
      run: |
        ssh qleqs@bumblebee.giize.com "cd containers/Raqin-website/Portfolio/ && git pull"
