name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to server
      run: |
        ssh user@yourserver "cd /path/to/your/project && git pull"

